# Generated by Django 5.1.1 on 2024-09-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='D:\\Tarianingsih\\PBP\\wowla-shop\x07ssets\\images (4).jpeg', upload_to=''),
        ),
    ]
